version: '3'
services:
  higanbana:
    entrypoint: ['java','-jar','/var/app.jar']
    network_mode: 'host'
    image: 'openjdk:15.0.2-oracle'
    environment:
      - TZ="Asia/shanghai"
    volumes:
      - ./higanbana-sorrow-1.0-SNAPSHOT.jar:/var/app.jar
    container_name: higanbana